### ISSUE TITLE
SSM distributor association on schedule is failing.

### ISSUE THREAD

**Issue by drey143** [CrowdStrike/aws-ssm-distributor#57] opened 2023-07-31 21:37 UTC
Scheduled assocation is failing with the error below, the same scheduled association was successful earlier today and I haven't made any changes to it. I have example of the failure output and success output.

```
Execution id | Association version | Status | Detailed status | Created date | Resource status
-- | -- | -- | -- | -- | --
262fa39f-c9c2-4641-b671-286b2f757c31 | 1 | Failed | InvalidAutomationParameters | Mon, 31 Jul 2023 21:11:49 GMT |  
5d0d66af-88ef-46ca-9492-7f725e9ded55 | 1 | Failed | InvalidAutomationParameters | Mon, 31 Jul 2023 20:42:05 GMT

Association version
Status
Detailed status
Created date
Resource status
[262fa39f-c9c2-4641-b671-286b2f757c31](https://us-east-2.console.aws.amazon.com/systems-manager/state-manager/5a7f5ce0-5f3a-4d9a-a69c-09ea7e4b9ef3/executionTarget/262fa39f-c9c2-4641-b671-286b2f757c31?region=us-east-2)	1	
 
Failed
InvalidAutomationParameters	Mon, 31 Jul 2023 21:11:49 GMT	
[5d0d66af-88ef-46ca-9492-7f725e9ded55](https://us-east-2.console.aws.amazon.com/systems-manager/state-manager/5a7f5ce0-5f3a-4d9a-a69c-09ea7e4b9ef3/executionTarget/5d0d66af-88ef-46ca-9492-7f725e9ded55?region=us-east-2)	1	
 
Failed
InvalidAutomationParameters	Mon, 31 Jul 2023 20:42:05 GMT


Success
Success	Mon, 31 Jul 2023 11:11:51 GMT	Success:8
[61d6bb28-d2da-42f3-91b8-d0f996d0e553](https://us-east-2.console.aws.amazon.com/systems-manager/state-manager/5a7f5ce0-5f3a-4d9a-a69c-09ea7e4b9ef3/executionTarget/61d6bb28-d2da-42f3-91b8-d0f996d0e553?region=us-east-2)	1	
 
Success
Success	Mon, 31 Jul 2023 10:41:59 GMT

**Comment by ffalor** [comment] 2023-08-01 02:23
No changes have been made to the automation document. What parameters are you passing to the document?

**Comment by drey143** [comment] 2023-08-01 14:51
@ffalor the same automation document association was deployed in other regions and worked fine but it's failing in "US-EAST-2" region

**Comment by ffalor** [comment] 2023-08-01 15:32
I checked, and the automation document in us-east-2 is the same as the other regions. The docs in both regions have the same parameter requirements. 

`InvalidAutomationParameters` is the only error in the content you sent which points to a missing automation parameter or an association created with the a non existent automation parameter. When you go to your automation association and click on `parameters` are they the exact same as the association that is sucessful?

**Comment by drey143** [comment] 2023-08-01 15:34
@ffalor yes both sucessful and failed association were created using the same CloudFormation Template

**Comment by ffalor** [comment] 2023-08-01 15:50
If it's still failing - I'd open a ticket with Amazon Support to investigate. I was able to confirm that documents are the same in these regions, so they have the same requirements.

**Comment by ffalor** [comment] 2023-08-09 17:07
I will close this, if aws determines the issue is related to our document feel free to comment back.

**Closed by ffalor** 2023-08-09 17:07 UTC
Labels: triage
